#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#88C0D0"
bspc config normal_border_color "#e6eef3"
bspc config active_border_color "#eceff4"
bspc config presel_feedback_color "#98C379"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --bg-fill /home/javi/Imágenes/ice_original.jpg
$HOME/.config/polybar/launch.sh
picom --experimental-backends &
bspc config border_width 0
bspc config focus_follows_pointer true
xsetroot -cursor_name left_ptr &
